#%RAML 1.0 NamedExample
  value:
    projectName: 'SVS SYSTEM'
    projectDesc: 'Signiture Verification System upgrade 2.3v'
    projectStart: 'July 19, 2023'
    projectEnd: 'February 12, 2024'
    projectBudg: '600000'