#%RAML 1.0 DocumentationItem
title: B-TRANS
content: |
  **B-TRANS** enables developers to build applications that make use of the information from resource  methods implemented in the API.

  This API contains functionality that allows developers to retrieve and manipulate _customer_, _account_ and _transaction_ information. Check out the [API Portal]() for more details.